### ISSUE TITLE
Adding ppc64le support to signal

### ISSUE THREAD

**Issue by seth-priya** [tailhook/signal#7]
Hi,

Signal is currently not supported on ppc64le and the main cause of that is the dependency on nix 0.6, which did not have support for ppc64le.

nix has recently been ported to Power LE and using the mainline version of nix, and with some code changes in support of that, I have been able to build signal successfully on ppc64le.

I wanted to understand, if apart from using "cargo test", there is any additional testing that I should do to test my changes?

Thanks for the help!!

Regards,
Priya

**Comment by tailhook** [comment]
You can also run examples. Otherwise, feel free to submit a pull request.

I also usually test the package as part of [vagga](http://github.com/tailhook/vagga) before a release, though. But this is too much to require for pull request (especially given that vagga is too big to easily port it to the platform).

Looking forward to your PR.

**Comment by seth-priya** [comment]
Thanks @tailhook, for the quick response, I will run the example. 

Also. since, my work is currently based on nix mainline which might be subject to changes, I was discussing with them regarding the release plan for their next release that will include ppc64le changes and found that 0.9 would be out in next week. I think it would make sense to wait till then and base my changes on that - effectively upgrade signal to use nix to 0.9.0.

I will test the current changes till then and repeat the testing once 0.9.0 is out and raise a PR.

Please let me know if that sounds fine to you as well or if you have some additional thoughts? Thanks!

**Comment by tailhook** [comment]
Sounds fine. Thanks!

**Comment by seth-priya** [comment]
Hi @tailhook, I have updated my patch to use nix 0.9.0 and cargo build succeeds with the changes.

However, seems like no tests are running with "cargo test"
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/signal-37cd97b775af82c2

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests signal

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

Is there another way to run the examples locally that I might be missing? Please suggest. Thanks!

**Comment by seth-priya** [comment]
I checked the travis-ci logs @https://travis-ci.org/tailhook/signal/jobs/259343634 and they are similar to what I see on ppc64le as well

**Comment by tailhook** [comment]
Yes. It's hard to test signals since tests by default are in-process. So yes we don't have tests here. If you have good ideas how to make tests I'll be happy to accept PRs. As I have said I'm mostly testing signal library as part of [vagga](https://github.com/tailhook/vagga) and other projects of mine.

Released signal v0.4.0.

**Comment by seth-priya** [comment]
Thanks @tailhook - I will have a look at this! Thanks for your support.
